# Generated by Django 5.1.3 on 2025-10-05 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date"]},
        ),
    ]
